blog_title: Deelan.
footer_text: "Built with â™¥ using Deelan."
default_theme: dark
timezone: America/Los_Angeles
accent_hue: 150
content_max_width: 1100px
code_theme_light: material-theme-lighter
code_theme_dark: material-theme-darker
timeline_commit_url_template: https://github.com/jhadida/deelan/commit/${COMMIT_SHA}
