site_name: DEELAN
site_description: Data Engineering Electronic LAboratory Notebook
site_url: https://jhadida.github.io/deelan
repo_url: https://github.com/jhadida/deelan
repo_name: jhadida/deelan

site_dir: .site-docs

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CLI: cli.md
  - Analytics: analytics.md
  - Authoring: authoring.md
  - Configuration: configuration.md
  - Tag CLI: tag-cli.md
  - Editor Integration: editor-integration.md
  - Developer Notes: developer.md
  - Search Grammar: search-grammar.md
  - PWA: pwa.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight
